### ISSUE TITLE
how to delete list mode detector?

### ISSUE THREAD

**Issue by ghost** [hnordquist/INCC6#23]
<a href="https://github.com/henzlova"><img src="https://avatars.githubusercontent.com/u/11947976?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [henzlova](https://github.com/henzlova)**
_Tue May 19 18:52:36 2015_
_Originally opened as https://github.com/hnordquist/INCC6-WithHistory/issues/81_

---

When using 'add detector' to create a new detector associated with list mode acquisition the detectors gets correctly created, but does not show up in 'delete detector' scroll-bar menu.

Also if a shift register detector gets deleted and subsequently recreated using the same name an 'unhandled exception' occurs.

**Comment by ghost** [comment]
<a href="https://github.com/jflongo"><img src="https://avatars.githubusercontent.com/u/6966430?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jflongo](https://github.com/jflongo)**
_Wed May 20 02:35:31 2015_

---

Can you post the log fragment that shows the exception? This will help pinpoint the cause.
Look first at the logs in c:\temp\2015-0519, or if you've set the logging location elsewhere, look there.
Exceptions are usually caught and logged.

**Comment by ghost** [comment]
<a href="https://github.com/hnordquist"><img src="https://avatars.githubusercontent.com/u/5940271?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hnordquist](https://github.com/hnordquist)**
_Wed May 20 13:16:45 2015_

---

I can look at this when I get to office...

**Comment by ghost** [comment]
<a href="https://github.com/hnordquist"><img src="https://avatars.githubusercontent.com/u/5940271?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hnordquist](https://github.com/hnordquist)**
_Wed May 20 13:17:25 2015_

---

Need you to look at issue I sent yesterday with luv results different from
file input for LM

**Comment by ghost** [comment]
<a href="https://github.com/henzlova"><img src="https://avatars.githubusercontent.com/u/11947976?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [henzlova](https://github.com/henzlova)**
_Wed May 20 14:17:26 2015_

---

Attempt to re-create the SR detector after deleting it:

System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at NCC.IntegrationHelpers.CreateDetectorWithAssociations(Detector model, String NewId, String EId, String atype, InstrType rtype)
   at NewUI.IDDDetectorAdd.OKButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by ghost** [comment]
<a href="https://github.com/hnordquist"><img src="https://avatars.githubusercontent.com/u/5940271?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hnordquist](https://github.com/hnordquist)**
_Wed May 20 20:22:54 2015_

---

I will handle the add/delete detector issues here tomorrow.

**Comment by ghost** [comment]
<a href="https://github.com/hnordquist"><img src="https://avatars.githubusercontent.com/u/5940271?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hnordquist](https://github.com/hnordquist)**
_Thu May 21 00:24:17 2015_

---

Daniele,

I started to look at this today.  I will fix the mess tomorrow! :-)

**Comment by ghost** [comment]
<a href="https://github.com/jflongo"><img src="https://avatars.githubusercontent.com/u/6966430?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jflongo](https://github.com/jflongo)**
_Wed Jun  3 08:01:03 2015_

---

There were several issues with DB storage of detector and params that were introduced and now have been fixed by recent commits. So your DB should be reset and start over with your definitions.

But I need to make another DB modification, this time to the measurements table.
The database measurements table has a foreign key to the associated detector, so deleting a detector impacts the measurement relationship and indirectly many other database entries related to the measurement, 

Deleting a detector must delete only the directly associated parameters  (INCC5 normalization, background, SR params, unattended params, add-a-source params, and if a LM the new LM params).
Measurements  have a copy of the detector details stored in the results_rec. There is no need to delete a measurement or the related  cycles.
The database will need an update again.

**Comment by ghost** [comment]
<a href="https://github.com/jflongo"><img src="https://avatars.githubusercontent.com/u/6966430?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jflongo](https://github.com/jflongo)**
_Wed Jun  3 12:40:01 2015_

---

These are the tables that relate to a detector. Some are required. Most are optional.
The updated database schema includes a delete cascade condition for each table.
So only the in-memory lists of each permanent type need to be refreshed after a detector deletion.
I.e DetectorList, and the related maps. 
active_rec
active_mult_rec
active_passive_rec
add_a_source_rec
cal_curve_rec
collar_rec
collar_detector_rec
collar_k5_rec
curium_ratio_rec
known_alpha_rec
known_m_rec
multiplicity_rec
analysis_method_rec
add_a_source_setup_rec
alpha_beta_rec
bkg_parms_rec
sr_parms_rec
sr_parms_ext
stratum_id_detector
stratum_id_instances
tm_bkg_parms_rec
unattended_parms_rec
LMNetComm
LMHWParams
LMAcquireParams
CountingParams
LMMultiplicity
HVCalibrationParams
.

**Comment by ghost** [comment]
<a href="https://github.com/jflongo"><img src="https://avatars.githubusercontent.com/u/6966430?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jflongo](https://github.com/jflongo)**
_Fri Jun 19 10:00:49 2015_

---

Had to make one more fix for this. I think it works now. I changed it so it does not delete measurements (for now). That could be an option rather than a required result.

**Comment by ghost** [comment]
<a href="https://github.com/hnordquist"><img src="https://avatars.githubusercontent.com/u/5940271?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hnordquist](https://github.com/hnordquist)**
_Mon Jun 22 19:29:15 2015_

---

Daniela and I did a bunch of delete/add functions this morning for shift registers.  Perhaps we can close this if she can do the same with list mode instruments?

**Comment by ghost** [comment]
<a href="https://github.com/henzlova"><img src="https://avatars.githubusercontent.com/u/11947976?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [henzlova](https://github.com/henzlova)**
_Tue Jun 23 17:24:00 2015_

---

The shift register also seems to work for me, but the list mode does not seem to be quite there yet. I can delete a detector previously created without any problems, but when the same detector is added I still get an 'unhandled exception':

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at NCC.IntegrationHelpers.CreateDetectorWithAssociations(Detector model, String newId, String elecId, String typeDesc, InstrType srType) in c:\code\2013sandbox\INCC6\Defs\Central.cs:line 342
   at NewUI.IDDDetectorAdd.OKButton_Click(Object sender, EventArgs e) in c:\code\2013sandbox\INCC6\UI\NewUI\FormsHappyPlace\IDDDetectorAdd.cs:line 106
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

INCC6
    Assembly Version: 0.9.7.17285
    Win32 Version: 0.9.7.17285

##     CodeBase: file:///C:/INCC6/deployment06-22-2015/INCC6.exe

PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209

##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll

WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34238 built by: FX452RTMGDR

##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll

System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll

PresentationFramework.Aero
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero.dll

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR

##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll

RepDB
    Assembly Version: 0.9.7.17285
    Win32 Version: 0.9.7.17285

##     CodeBase: file:///C:/INCC6/deployment06-22-2015/RepDB.DLL

Defs
    Assembly Version: 0.9.7.17285
    Win32 Version: 0.9.7.17285

##     CodeBase: file:///C:/INCC6/deployment06-22-2015/Defs.DLL

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34251 built by: FX452RTMGDR

##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

NCCCtrl
    Assembly Version: 0.9.7.17285
    Win32 Version: 0.9.7.17285

##     CodeBase: file:///C:/INCC6/deployment06-22-2015/NCCCtrl.DLL

Options
    Assembly Version: 1.2.0.0
    Win32 Version: 1.2.0.0

##     CodeBase: file:///C:/INCC6/deployment06-22-2015/Options.DLL

System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll

System.Data.OracleClient
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_32/System.Data.OracleClient/v4.0_4.0.0.0__b77a5c561934e089/System.Data.OracleClient.dll

System.Data.SQLite
    Assembly Version: 1.0.94.0
    Win32 Version: 1.0.94.0

##     CodeBase: file:///C:/INCC6/deployment06-22-2015/System.Data.SQLite.DLL

System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll

System.Data.Entity
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Data.Entity/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Entity.dll

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll

Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 12.0.51209.34209 built by: FX452RTMGDR

##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll

System.Deployment
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34244 built by: FX452RTMGDR

##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Deployment/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll

PresentationFramework-SystemXml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209

##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXml/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXml.dll

PresentationFramework-SystemData
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209

##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemData/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemData.dll

UIAutomationProvider
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll

LMSR
    Assembly Version: 0.9.5246.27500
    Win32 Version: 0.9.5246.27500

##     CodeBase: file:///C:/INCC6/deployment06-22-2015/LMSR.DLL

NCCCore
    Assembly Version: 0.3.12.15
    Win32 Version: 0.3.12.15

##     CodeBase: file:///C:/INCC6/deployment06-22-2015/NCCCore.DLL

Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by ghost** [comment]
<a href="https://github.com/jflongo"><img src="https://avatars.githubusercontent.com/u/6966430?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jflongo](https://github.com/jflongo)**
_Tue Jun 23 18:35:24 2015_

---

ok that wil be a simple fix

**Comment by ghost** [comment]
<a href="https://github.com/jflongo"><img src="https://avatars.githubusercontent.com/u/6966430?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jflongo](https://github.com/jflongo)**
_Tue Jun 23 19:33:17 2015_

---

The latest release has INCC6.exe, INCCCmd.exe, Defs.ll, RepDB.dll and
NCCCtrl.dll at 0.9.7.17300. The csv output files list the assemblies in
use, with version numbers.

**Comment by ghost** [comment]
<a href="https://github.com/jflongo"><img src="https://avatars.githubusercontent.com/u/6966430?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jflongo](https://github.com/jflongo)**
_Wed Jun 24 09:01:27 2015_

---

The detector param collections have deletion and removal stubs.
So you will see changes to the collection interfaces for the detector param maps to support map removal and database deletion.
Database deletion actually happens automatically because of the DELETE CASCADE table constraint, so the implementation will simply check to see if the pram is delete, while removing it from the in-memory map.

**Comment by ghost** [comment]
<a href="https://github.com/jflongo"><img src="https://avatars.githubusercontent.com/u/6966430?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jflongo](https://github.com/jflongo)**
_Wed Jun 24 20:56:16 2015_

---

Like last week's overwrite for #58, another recent commit overwrote my fix for #81. So I made the choice to restore it.

**Comment by ghost** [comment]
<a href="https://github.com/hnordquist"><img src="https://avatars.githubusercontent.com/u/5940271?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hnordquist](https://github.com/hnordquist)**
_Wed Jun 24 21:11:06 2015_

---

I saw your delete stuff.  I didn't overwrite.  Anyhow, I will grab latest
stuff.

**Comment by ghost** [comment]
<a href="https://github.com/jflongo"><img src="https://avatars.githubusercontent.com/u/6966430?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jflongo](https://github.com/jflongo)**
_Thu Jun 25 09:34:25 2015_

---

I am close to fixing the existing key errors in LM

**Comment by ghost** [comment]
Commit d37be607d965a8dafe6b88e711758ce311b28000 cleared up the remaining DB schema problems with this

**Comment by ghost** [comment]
Deletion finalized in ee682d8212dabc44ff851de59a0636c5010b301a
